### ISSUE TITLE
RSS module commands failing

### ISSUE THREAD

**Issue by vesatoivonen** [lepinkainen/pyfibot#203]
On Ubuntu 14.04.4 I get the following errors when running RSS module commands:

```
[2016-05-21 17:07:27,983][INFO     ][module_rss     ]  Updating RSS feeds started
[2016-05-21 17:07:33,191][ERROR    ][sqlalchemy.pool.StaticPool]  Exception during reset or similar
Traceback (most recent call last):
  File "/home/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/home/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/home/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id -1264583872 and this is thread id -1275069632

```

**Comment by vesatoivonen** [comment]
Same thing with docker.

**Comment by aapa** [comment]
The problem is caused because of the bot design. Different IRC networks run in separate threads and SQLite only allows access from one thread. The problem has been known for a long time but is relatively hard to fix. Also the upcoming bot rewrite would fix this anyway so incentive to fix it on this version is not that big.

This bug can be avoided by running pyfibot in only one network at a time OR probably by switching to another database supported by SQLAlchemy, e.g. MySQL or PostgreSQL. If you decide to try the latter solution, please report if it works, since a different database could be implemented as a default setting to Docker version at least (I think?)

**Comment by vesatoivonen** [comment]
I'm unable to get SQLite working even when running pyfibot on one network.
I'll try how it goes with MariaDB.

**Comment by aapa** [comment]
Ok, then this is probably a completely new bug. I'll try to reproduce it during this week.

**Comment by lepinkainen** [comment]
```
[2016-05-23 13:28:35,574][ERROR    ][sqlalchemy.pool.StaticPool]  Exception during reset or similar  (pool.py:643)
Traceback (most recent call last):
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 3631472334592 and this is thread id 3631344363264
[2016-05-23 13:28:35,609][ERROR    ][sqlalchemy.pool.StaticPool]  Exception closing connection <sqlite3.Connection object at 0x34d7eb67688>  (pool.py:293)
Traceback (most recent call last):
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 290, in _close_connection
    self._dialect.do_close(connection)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 426, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 3631472334592 and this is thread id 3631344363264
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/users/shrike/projects/pyfibot/pyfibot/modules/module_rss.py", line 316, in update
    self.read()
  File "/home/users/shrike/projects/pyfibot/pyfibot/modules/module_rss.py", line 291, in read
    self.__save_item(i, tbl)
  File "/home/users/shrike/projects/pyfibot/pyfibot/modules/module_rss.py", line 235, in __save_item
    if not table.find_one(title=item['title'], link=item['link']):
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/dataset/persistence/table.py", line 344, in find_one
    iterator = self.find(*args, **kwargs)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/dataset/persistence/table.py", line 401, in find
    rp = self.database.executable.execute(count_query)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1334, in _handle_dbapi_exception
    self._autorollback()
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 791, in _autorollback
    self._root._rollback_impl()
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 670, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1266, in _handle_dbapi_exception
    exc_info
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 668, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/home/users/shrike/projects/pyfibot/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 3631472334592 and this is thread id 3631344363264

```

**Comment by vesatoivonen** [comment]
I managed to get RSS working (without docker) by disabling all the other modules and using MariaDB as database. SQLite kept failing even when there were no other modules in use

**Comment by lepinkainen** [comment]
This is something that has worked for a year or so without any problems, now an update to either Dataset or SQLAlchemy broke something and started giving this weird error.
